#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# My settings
#

# focudes window border in red
bspc config focused_border_color '#ff0000'
# lauch polybar
$HOME/.config/polybar/launch.sh
# setting touchpad
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
# setting screen resolution
xrandr --output LVDS-1 --scale 1.125x1.125
# seiing screen brightness
xrandr --output LVDS-1 --brightness 0.8
# setting wallpapers
feh --randomize --bg-scale $HOME/Pictures/wallpapers
# volume icon
pgrep -x volumeicon > /dev/null || volumeicon &
# keyboard
setxkbmap -variant alt-intl
